---
title: "Assignment 3 - Task 3"
author: "Aya Rosenfeld"
date: "11/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(janitor)
library(here)
library(kableExtra)
library(lubridate)
```



```{r}
urchins <- read_csv(here("data", "urchins.csv")) %>% 
  clean_names()
```

```{r}
ggplot(data = urchins, aes(x = size)) +
  geom_histogram() +
  facet_wrap(~common_name) +
  labs(x = "Size (cm)", y = "Number of Urchins", title = "Size Differences Between Urchin Species") +
  theme_minimal()
```

```{r}
ggplot(data = urchins, aes(x = common_name, y = size)) +
  geom_boxplot() +
  labs(x = "Urchin Species", y = "Size (cm)", title = "Size Differences Between Urchin Species") +
  theme_minimal()
```


```{r}
urchin_summary <- urchins %>% 
  group_by(common_name) %>% 
  summarize(mean_size = mean(size),
            med_size = median(size),
            sd_size = sd(size),
            n = n())

kbl(urchin_summary) %>% 
  kable_styling()

```

takeaway 2-3 sentence


Section 2:


```{r}
purple_urchins <- urchins %>% 
  filter(common_name == "Purple Urchin") %>% 
  mutate(date = mdy(date)) %>% 
  mutate(year = year(date)) %>% 
  mutate(site_full = case_when(
    site == "NAPL" ~"Naples Reef",
    site == "AQUE" ~"Arroyo Quemado Reef",
    site == "CARP" ~"Carpinteria Reef",
    site == "MOHK" ~"Mohawk Reef",
    site == "IVEE" ~"Isla Vista Reef"
  ))

purple_urchin_summary <- purple_urchins %>% 
  group_by(site_full, year) %>% 
  count(year)

kbl(purple_urchin_summary) %>% 
  kable_styling()
```

```{r}
ggplot(data = purple_urchin_summary, aes(x = year, y = n)) +
  geom_col(aes(color = site_full)) +
  facet_wrap(~site_full) +
  labs(x = "Year", y = "Number of Urchins", title = "Size Differences Between Sites")
```





